//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieWebsiteEntities : DbContext
    {
        public MovieWebsiteEntities()
            : base("name=MovieWebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Celebrity> Celebrities { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<MovieCast> MovieCasts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<MovieReview> MovieReviews { get; set; }
        public virtual DbSet<NewComment> NewComments { get; set; }
        public virtual DbSet<NewCommentReply> NewCommentReplies { get; set; }
        public virtual DbSet<SubMenu> SubMenus { get; set; }
    }
}
